<?php if(Mage::getStoreConfig('blog/menu/show_recent_post')):?>
<?php 
	$helperBlog = Mage::helper('blog');
	$thumnailWidth = Mage::getStoreConfig('blog/info/recent_thumbnail_width');
	$thumnailHeight = Mage::getStoreConfig('blog/info/recent_thumbnail_height');
?>
<div class="block em_block-recent-post">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recent Posts'); ?></span></strong>
    </div>
    <div class="block-content">
        <ol>
            <?php foreach ($this->getRecentPost() as $p): ?>
                <li class="item">
					<?php if($p->getImage()):?>
					<a href="<?php echo $p->getPostUrl();?>">
						<img src="<?php echo $helperBlog->resizeImage($p->getImage(),$thumnailWidth,$thumnailHeight,"emblog/post",'thumbnail');?>" alt="" />
					</a>
					<?php endif;?>
                    <a class="post-title" href="<?php echo $p->getPostUrl(false);?>" ><?php echo $p->getTitle();?></a>
                    <?php 
						$shortdes =  $p->getPostIntro();
						if(strlen($shortdes)>100) { //dem ki tu chuoi $str, 10o la chieu dai muon quy dinh
							$strCutTitle = substr($shortdes, 0, 100); //cat 100 ki tu dau
							$shortdes = substr($strCutTitle, 0, strrpos($strCutTitle, ' '));
						}
					?>
					<div class="desc"><?php echo $shortdes;?></div>
					<p><a href="<?php echo $p->getPostUrl();?>" title="" class="cls_view"><?php echo $this->__("Read more") ?></a></p>                    
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif;?>