<?php
$model = Mage::getModel("core/email_template_filter");
$data = $this->getMegamenupro();
$menu = $data['content'];
//echo '<pre>';print_r($menu);

$container_css = '';
$menuid = $this->getData('menu');
$setId = $menuid . '_' . rand(1, 9999);
?>

<style>

    .menu-item-text a h5 {
        padding-top: 10px;
        padding-bottom: 0px;
        margin: 0;
        -webkit-margin-before: 0;
        -webkit-margin-after: 0;
        -webkit-margin-start: 0;
        -webkit-margin-end: 0px;
    }

    .alpha{

        margin: 0;
        padding: 0;
    }


    .em_nav ul.hnav .menu-container
    {
        padding: 0;
        margin: 0;
    }

    .hnav .menu-item-depth-0:hover > .menu-container{
        margin-top: 9px;
        padding: 0px;
        left: 0px;
    }
    
    .em_nav h5.m-line, li.menu-container:first-child h5 {
         padding-top: 10px;
        padding-bottom: 0px;
        margin: 0;
        -webkit-margin-before: 0;
        -webkit-margin-after: 0;
        -webkit-margin-start: 0;
        -webkit-margin-end: 0px;
        padding-left: 10px;
margin-right: 10px;
    }
    
    .em_nav .menu-item-depth-0 .menu-item-text a {
        padding: 3px 0 17px;
        padding-left: 0px!important;
         padding-right: 0px!important;
    }   
    .menu-item-text a h5:hover{
     color: #A76528;   
    }
    
    .menu-item-vbox > .menu-container > li {
        padding: 0px;
        margin: 0px;
}
    
</style>
<?php if (!empty($menu)): ?>
    <div class="megamenu-wrapper wrapper-<?php echo $setId; ?>">
        <div class="menu-title" id="displayMenu_<?php echo $setId; ?>"><a href="javascript:void(0)"><?php echo $this->__('Navigation') ?></a><span class="option">nav</span></div>
        <div class="em_nav" id="toogle_menu_<?php echo $setId; ?>">
            <ul class="<?php echo $data['type'] == 1 ? 'vnav' : 'hnav' ?> <?php echo $data['css_class'] ?>">
                <?php $close_tags = array() ?>
                <?php foreach ($menu as $i => $item): ?>
                    <?php $is_parent = ($i < count($menu) - 1) && $menu[$i + 1]['depth'] > $item['depth'] ?>
                    <?php echo $this->open_tag($close_tags, $item['depth'], $container_css) ?>

                    <?php echo $this->close_tags($close_tags, $item['depth']) ?>

                    <?php /* ---------- Menu Item: LINK ---------- */ ?>
                    <?php if ($item['type'] == 'link'): ?>
                        <li class="menu-item-link menu-item-depth-<?php echo $item['depth'] ?> <?php echo $item['css_class'] ?> <?php echo $is_parent ? 'menu-item-parent' : '' ?>">
                            <a href="<?php echo $model->filter($item['url']) ?>" 
                            <?php if ($item['target']): ?>
                                   target="<?php echo htmlspecialchars($item['target']) ?>"
                               <?php endif ?>
                               ><span><?php echo $item['label'] ?></span>
                                   <?php if ($item['sublabel']): ?>
                                    <small><?php echo $item['sublabel'] ?></small>
                                <?php endif ?>
                            </a>
                            <?php $close_tags[$item['depth']] = "</li>" ?>

                        <?php endif ?>


                        <?php /* ---------- Menu Item: TEXT ---------- */ ?>
                        <?php if ($item['type'] == 'text'): ?>
                        <li class="menu-item-text menu-item-depth-<?php echo $item['depth'] ?> <?php echo $item['css_class'] ?> <?php echo $is_parent ? 'menu-item-parent' : '' ?>">
                            <?php echo $item['text'] ?>
                            <?php $close_tags[$item['depth']] = "</li>" ?>
                        <?php endif ?>


                        <?php /* ---------- Menu Item: HBOX ---------- */ ?>
                        <?php if ($item['type'] == 'hbox'): ?>
                        <li class="menu-item-hbox menu-item-depth-<?php echo $item['depth'] ?> <?php echo $item['css_class'] ?> <?php echo $is_parent ? 'menu-item-parent' : '' ?>" style="<?php
                        echo $item['width'] ? 'width:' . $item['width'] . 'px;' : '';
                        echo $item['height'] ? 'height:' . $item['height'] . 'px;' : '';
                        echo $item['spacing'] ? 'padding:' . $item['spacing'] . 'px;' : '';
                        ?>">
                                <?php $close_tags[$item['depth']] = "</li>" ?>
                            <?php endif ?>


                        <?php /* ---------- Menu Item: VBOX ---------- */ ?>
                        <?php if ($item['type'] == 'vbox'): ?>
                        <li class="menu-item-vbox menu-item-depth-<?php echo $item['depth'] ?> <?php echo $item['css_class'] ?> <?php echo $is_parent ? 'menu-item-parent' : '' ?>" style="<?php
                            echo $item['width'] ? 'width:' . $item['width'] . 'px;' : '';
                            echo $item['height'] ? 'height:' . $item['height'] . 'px;' : '';
                            echo $item['spacing'] ? 'padding:' . $item['spacing'] . 'px;' : '';
                            ?>">
                                <?php $close_tags[$item['depth']] = "</li>" ?>
                            <?php endif ?>

                        <?php $container_css = $item['container_css'] ?>
                    <?php endforeach ?>

                    <?php echo $this->close_tags($close_tags, 0); ?>
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        var checkPhone = /iPhone|iPod|Phone|Android/i.test(navigator.userAgent);
        function toogleMenuPro_<?php echo $setId; ?>() {
            var $ = jQuery;
            var container = $("#toogle_menu_<?php echo $setId; ?>");
            var textClick = $("#displayMenu_<?php echo $setId; ?>");
            var parentClick = $(".wrapper-<?php echo $setId; ?>").parent().first().parent().first();
            if (($(window).width() <= 760 || checkPhone == true) && !(parentClick.hasClass("menu-left")))
            {

                textClick.show();
                container.hide();
                textClick.unbind('click');
                textClick.bind('click', function () {
                    container.slideToggle();
                });
            } else {
                textClick.hide();
                container.show();
            }
        }
        ;

        jQuery(document).ready(function () {
            toogleMenuPro_<?php echo $setId; ?>();
        });

        //jQuery(window).bind('emadaptchange orientationchange', function() {
        jQuery(window).resize(function () {
            toogleMenuPro_<?php echo $setId; ?>();

        });
    </script>
    <?php
 endif ?>